### ISSUE TITLE
ux thought: maybe it should be possible to un-open a card?

### ISSUE THREAD

**Issue by silky** [hyperlink-academy/garden#24]
love the website; it has a very calming vibe.

i note the following behaviour.

by default, cards aren't open:

![image](https://github.com/hyperlink-academy/garden/assets/129525/4b59c5cf-5c9a-4eff-a388-f8939490abc6)

once you click on one, it opens

![image](https://github.com/hyperlink-academy/garden/assets/129525/a8845e8d-ddfb-4c02-b31f-db771a10d1f9)

it'd be nice and relaxing if i could actually close that card, once i've thought about it; but i don't think there is such an option! :)

**Comment by bschlagel** [comment]
Hi, thanks for the suggestion! We used to have a way to close cards, as well as see more of a history stack of previously opened cards, and simplified to just current open card per-room (when we added multiple rooms), but we'll likely revisit to bring back some of that behavior in the future.

For now as a workaround, reloading the page will effectively close the card, but agree it'd be nice to be able to do so intentionally within the app :)

**Comment by bschlagel** [comment]
@silky Just noting we added this! Now a history stack so you can navigate to previously viewed cards and close the card if it's the last in the stack (from upper left of the card).
