### ISSUE TITLE
when creating multiple cards in a row, the previous title you typed in appears on the second attempt

### ISSUE THREAD

**Issue by silky** [hyperlink-academy/garden#25]
i would expect this should be cleared if the card was actually created (it was).

**to reproduce:**

1. double-click to make a new card, type a title,
2. enter some text in the body; click off somewhere
3. double-click again to make _another_ card, observe that the title is already filled in with the original one!

**expected behaviour:**

it would be empty; just as it was the first time!

**Comment by jaredpereira** [comment]
Thanks for the report! Should be fixed by https://github.com/hyperlink-academy/garden/commit/31ba01d31a61382baa73c5041fd104b483d2baa1

I went with just clearing the field when the modal is opened/closed which I think is the most predictable behavior.

**Comment by silky** [comment]
thanks for the prompt response!

> I went with just clearing the field when the modal is opened/closed which I think is the most predictable behavior.

probably that's fine; but for what it's worth i think places like github/trello etc only do the clearing on commiting the save, in part because it's a convenient way to save a draft, and in part because - and this happened to me a few times - you can accidentally close the card without meaning to, before saving it! :)
