### ISSUE TITLE
you can generate a lot of emoji's by repeatedly clicking the icon

### ISSUE THREAD

**Issue by silky** [hyperlink-academy/garden#26]
![image](https://github.com/hyperlink-academy/garden/assets/129525/831abb3f-067b-4d6f-b57e-eea99f04f5aa)

not sure if this is the intention :)

**Comment by jaredpereira** [comment]
Ahaha yeah it was un-intentional at first but we left it in. So far we've mostly been using the reactions as tags so the multiples haven't been an issue. If it is getting in the way of a use case for you though happy to take out this feature/bug!

**Comment by silky** [comment]
i was trying to use it to see how many people had agreed to attend an event; i'd hope it would operate like github where i could see who clicked it; but it didn't work that way :)

maybe there's a better way to support that feature

**Comment by jaredpereira** [comment]
Hey @silky, just pushed up a fix for this! Sorry it took so long.
